// src/components/AllocationLegend/AllocationLegend.tsx
import "./AllocationLegend.css";
import type { AllocationSegment, CryptoSymbol, PortfolioAsset } from "@/types/exchangeRates";

interface AllocationLegendProps {
  segments: AllocationSegment[];
  activeSegmentIndex: number | null;
  currencyName: (symbol: CryptoSymbol) => string;
  formattedDollarAmount: (asset: PortfolioAsset) => string;
  formattedCryptoAmount: (asset: PortfolioAsset) => string;
  onShowSegment: (index: number) => void;
  onClearSegment: () => void;
}

export default function AllocationLegend({
  segments,
  activeSegmentIndex,
  currencyName,
  formattedDollarAmount,
  formattedCryptoAmount,
  onShowSegment,
  onClearSegment,
}: AllocationLegendProps) {
  return (
    <ul className="allocation-legend" aria-label="Crypto allocation breakdown">
      {segments.map((segment) => {
        const dollarAmount = formattedDollarAmount(segment.asset);
        const cryptoAmount = formattedCryptoAmount(segment.asset);
        return (
          <li key={segment.asset.id}>
            <button
              type="button"
              className={activeSegmentIndex === segment.index ? "active" : undefined}
              onMouseEnter={() => onShowSegment(segment.index)}
              onFocus={() => onShowSegment(segment.index)}
              onBlur={onClearSegment}
              onClick={() => onShowSegment(segment.index)}
            >
              <i style={{ backgroundColor: segment.color }} aria-hidden="true"></i>
              <span className="legend-asset">
                <b>{currencyName(segment.asset.symbol)}</b>
                {dollarAmount && <small>{dollarAmount}</small>}
              </span>
              {cryptoAmount && <strong>{cryptoAmount}</strong>}
            </button>
          </li>
        );
      })}
    </ul>
  );
}

// src/components/AllocationLegend/AllocationLegend.vue
<script setup lang="ts">
import "./AllocationLegend.css";
import type { AllocationSegment, CryptoSymbol, PortfolioAsset } from "../../types/exchangeRates";

defineProps<{
  segments: AllocationSegment[];
  activeSegmentIndex: number | null;
  currencyName: (symbol: CryptoSymbol) => string;
  formattedDollarAmount: (asset: PortfolioAsset) => string;
  formattedCryptoAmount: (asset: PortfolioAsset) => string;
}>();

const emit = defineEmits<{
  showSegment: [index: number];
  clearSegment: [];
}>();
</script>

<template>
  <ul class="allocation-legend" aria-label="Crypto allocation breakdown">
    <li v-for="segment in segments" :key="segment.asset.id"><button type="button" :class="{ active: activeSegmentIndex === segment.index }" @mouseenter="emit('showSegment', segment.index)" @focus="emit('showSegment', segment.index)" @blur="emit('clearSegment')" @click="emit('showSegment', segment.index)"><i :style="{ backgroundColor: segment.color }" aria-hidden="true"></i><span class="legend-asset"><b>{{ currencyName(segment.asset.symbol) }}</b><small v-if="formattedDollarAmount(segment.asset)">{{ formattedDollarAmount(segment.asset) }}</small></span><strong v-if="formattedCryptoAmount(segment.asset)">{{ formattedCryptoAmount(segment.asset) }}</strong></button></li>
  </ul>
</template>
