// src/components/CurrencyInput/CurrencyInput.tsx
import { useEffect, useRef, useState, type ChangeEvent, type ReactNode } from "react";
import "./CurrencyInput.css";
import { formatCurrencyInput, formatNumber } from "@/utils/formatters";

interface CurrencyInputProps {
  modelValue: number | null;
  onChange: (value: number | null) => void;
  label: string;
  inputId: string;
  placeholder: string;
  currencySymbol: string;
  errorMessage?: string;
  maxAmount?: number;
  action?: ReactNode;
}

function countDigitsBefore(value: string, position: number) {
  return (value.slice(0, position).match(/[\d.]/g) ?? []).length;
}
function positionAfterDigits(value: string, digitCount: number) {
  let seen = 0;
  for (let index = 0; index < value.length; index++) {
    if (seen >= digitCount) return index;
    if (/[\d.]/.test(value.charAt(index))) seen++;
  }
  return value.length;
}

export default function CurrencyInput({
  modelValue,
  onChange,
  label,
  inputId,
  placeholder,
  currencySymbol,
  errorMessage,
  maxAmount,
  action,
}: CurrencyInputProps) {
  // Typed-in display text; once the parent clears modelValue back to null
  // (e.g. "Clear amount"), the input renders empty regardless of this value.
  const [typedDisplayValue, setTypedDisplayValue] = useState("");
  const displayValue = modelValue === null ? "" : typedDisplayValue;
  const inputRef = useRef<HTMLInputElement | null>(null);
  const isFirstRender = useRef(true);

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      return;
    }
    if (modelValue === null) {
      inputRef.current?.focus();
    }
  }, [modelValue]);

  function updateValue(event: ChangeEvent<HTMLInputElement>) {
    const input = event.target;
    const previousValue = input.value;
    const cursorPosition = input.selectionStart ?? previousValue.length;
    const digitsBeforeCursor = countDigitsBefore(previousValue, cursorPosition);

    const formattedValue = formatCurrencyInput(previousValue);
    const shouldCapValue =
      maxAmount !== undefined &&
      formattedValue.numericValue !== null &&
      formattedValue.numericValue > maxAmount;
    const nextValue = shouldCapValue
      ? formatCurrencyInput(String(maxAmount))
      : formattedValue;

    setTypedDisplayValue(nextValue.displayValue);
    input.value = nextValue.displayValue;

    if (!shouldCapValue) {
      const nextCursorPosition = positionAfterDigits(nextValue.displayValue, digitsBeforeCursor);
      input.setSelectionRange(nextCursorPosition, nextCursorPosition);
    }

    onChange(nextValue.numericValue);
  }

  function formatOnBlur() {
    if (!displayValue) return;

    const [, decimalPart = ""] = displayValue.split(".");
    const hasDecimalDigits = decimalPart.length > 0;
    const numericValue = Number(displayValue.replace(/,/g, ""));

    if (Number.isFinite(numericValue)) {
      setTypedDisplayValue(formatNumber(numericValue, hasDecimalDigits ? 2 : 0, 2));
    }
  }

  return (
    <div className="currency-field">
      <div className="currency-field-heading">
        <label htmlFor={inputId}>{label}</label>
        {action}
      </div>

      <div className={`currency-input${errorMessage ? " invalid" : ""}`}>
        <span aria-hidden="true">{currencySymbol}</span>

        <input
          ref={inputRef}
          id={inputId}
          type="text"
          inputMode="decimal"
          placeholder={placeholder}
          autoComplete="off"
          value={displayValue}
          aria-invalid={Boolean(errorMessage)}
          aria-describedby={errorMessage ? `${inputId}-error` : undefined}
          onChange={updateValue}
          onBlur={formatOnBlur}
        />
      </div>

      {errorMessage && (
        <p id={`${inputId}-error`} className="currency-error" aria-live="polite" aria-atomic="true">
          {errorMessage}
        </p>
      )}
    </div>
  );
}

// src/components/CurrencyInput/CurrencyInput.vue
<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import "./CurrencyInput.css";
import { formatCurrencyInput, formatNumber } from "@/utils/formatters";

const {
  modelValue,
  label,
  inputId,
  placeholder,
  currencySymbol,
  errorMessage,
} = defineProps<{
  modelValue: number | null;
  label: string;
  inputId: string;
  placeholder: string;
  currencySymbol: string;
  errorMessage?: string;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: number | null];
}>();

const displayValue = ref("");
const inputElement = ref<HTMLInputElement | null>(null);

watch(
  () => modelValue,
  async (value) => {
    if (value === null) {
      displayValue.value = "";
      await nextTick();
      inputElement.value?.focus();
    }
  }
);

function updateValue(event: Event) {
  const input = event.target as HTMLInputElement;
  const formattedValue = formatCurrencyInput(input.value);

  displayValue.value = formattedValue.displayValue;
  input.value = displayValue.value;
  emit("update:modelValue", formattedValue.numericValue);
}

function formatOnBlur() {
  if (!displayValue.value) return;

  const [, decimalPart = ""] = displayValue.value.split(".");
  const hasDecimalDigits = decimalPart.length > 0;
  const numericValue = Number(displayValue.value.replace(/,/g, ""));

  if (Number.isFinite(numericValue)) {
    displayValue.value = formatNumber(
      numericValue,
      hasDecimalDigits ? 2 : 0,
      2
    );
  }
}
</script>

<template>
  <div class="currency-field">
    <label :for="inputId">{{ label }}</label>

    <div class="currency-input" :class="{ invalid: Boolean(errorMessage) }">
      <span aria-hidden="true">{{ currencySymbol }}</span>

      <input
        ref="inputElement"
        :id="inputId"
        type="text"
        inputmode="decimal"
        :placeholder="placeholder"
        autocomplete="off"
        :value="displayValue"
        :aria-invalid="Boolean(errorMessage)"
        :aria-describedby="errorMessage ? `${inputId}-error` : undefined"
        @input="updateValue"
        @blur="formatOnBlur"
      />
    </div>

    <p
      v-if="errorMessage"
      :id="`${inputId}-error`"
      class="currency-error"
      aria-live="polite"
      aria-atomic="true"
    >
      {{ errorMessage }}
    </p>
  </div>
</template>
